[package]
name = "async-actor"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.25"
env_logger = "0.7.1"
futures = "0.3.1"
log = "0.4.8"
tokio = { versio = "0.2.2", features = ["full"] }
tokio-codec = "0.1.1"
